#!/usr/bin/env bash

help () {
	echo -e "\nThis is a wrapper for launching TURFF"
	echo -e "usage: $0 -f env_config_file\n";
	echo "Options:"
	echo -e "-f cross compiler environment configuration file"
	echo -e "-h show this help menu"
	exit 1;
}

SUPERVISE=supervise
EXEC=/bin/turff/

while getopts ":hf:" opt; do
	case $opt in
		f)
			env_conf_file=$OPTARG
			;;
		h)
			help
			exit 1
			;;
		\?)
			echo "Invalid option: -$OPTARG"
			exit 1
			;;
		:)
			echo "Option -$OPTARG requires an argument."
			exit 1
			;;
	esac
done

if [ -n "$env_conf_file" ]; then
	source $env_conf_file
fi

if [ $? -eq 0 ] ; then
	$SUPERVISE $EXEC
else
	echo "Error setting up cross compiler environment"
fi
