#!/usr/bin/env bash

# This is a sanity test script for the CODI and toolchain Docker images.
# This script has to be run from the dockerfiles directory.
#
# Example:
#
# ../tests/build_containers

echo "Remove codi test image"
docker rmi crops/codi:test

echo "Remove toolchain test image"
docker rmi crops/toolchain:test

echo "Build CEED client"
make clean -C ../ceed/; make -C ../ceed/

echo "Build CODI test image"
docker build -t crops/codi:test -f Dockerfile.codi .

echo "Build toolchain test image"
docker build -t crops/toolchain:test -f Dockerfile.toolchain .

echo "Start CODI container"
docker run -d --name codi-test -v /var/run/docker.sock:/var/run/docker.sock --net=host crops/codi:test

echo "Start toolchain container 1"
docker run -d --name toolchain-test1 -v /crops/:/crops/ --env TURFFID=crops/toolchain:test1 --net=host crops/toolchain:test

echo "Start toolchain container 2"
docker run -d --name toolchain-test2 -v /crops/:/crops/ --env TURFFID=crops/toolchain:test2 --net=host crops/toolchain:test

echo "Start toolchain container 3"
docker run -d --name toolchain-test3 -v /crops/:/crops/ --env TURFFID=crops/toolchain:test3 --net=host crops/toolchain:test

echo "Start toolchain container 4"
docker run -d --name toolchain-test4 -v /crops/:/crops/ --env TURFFID=crops/toolchain:test4 --net=host crops/toolchain:test

echo "List containers known to CODI"
sleep 3; ../ceed/ceed -l

echo "Stop and remove toolchain containers"
docker stop toolchain-test1; docker rm toolchain-test1
docker stop toolchain-test2; docker rm toolchain-test2
docker stop toolchain-test3; docker rm toolchain-test3
docker stop toolchain-test4; docker rm toolchain-test4

echo "Stop and remove CODI test container"
docker stop codi-test; docker rm codi-test

