#!/usr/bin/env bash

# This is a sanity test script for the CODI and toolchain Docker images.
# This stops the test containers.
#
# Example:
#
# ./scripts/stop_containers

NAME_BASE="crops-toolchain-test"

II=0
Q=`docker ps -a | egrep ${NAME_BASE}${II} | awk '{print $1}'`
while [ "$Q" != ""  ]; do
    echo "Stop and Remove toolchain container $II"
    docker rm -f $Q || { echo 'docker rm $Q failed' ; exit 1; };
    let II=$II+1
    Q=`docker ps -a | egrep ${NAME_BASE}${II} | awk '{print $1}'`
done

echo "Stop and remove Zephyr test container"
Q=`docker ps -a | egrep zephyr-test | awk '{print $1}'`
if [ "$Q"  != "" ]; then
    echo "Removing Zephyr container"
    docker rm -f $Q || { echo 'docker rm $Q failed' ; exit 1; };
fi

echo "Stop and remove CODI test container"
Q=`docker ps -a | egrep codi-test | awk '{print $1}'`
if [ "$Q"  != "" ]; then
    echo "Removing codi container"
    docker rm -f $Q || { echo 'docker rm $Q failed' ; exit 1; };
fi
